# Executes commands at the start of an interactive session.

if [[ -s "$HOME/.profile" ]]; then . $HOME/.profile; fi;

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export PATH=$PATH:/usr/local/opt/go/libexec/bin:$HOME/go/bin

autoload -Uz add-zsh-hook promptinit
promptinit
prompt pure
