---

- hosts      : localhost
  connection : local

  vars_files :

    - vars/main.yml

    - vars/macos.yml
    - vars/macos.defaults.yml

  vars_prompt:

    - name: "mas_email"
      prompt: "Enter apple id"
      private: no

    - name: "mas_password"
      prompt: "Enter password"
      private: yes

  roles :

    # profiles account should be based upon

    - { role : profile/all,         tags : [ "profile-all"       ] }
    - { role : profile/developer,   tags : [ "profile-developer" ] }

    # optional roles

    - { role : system/wallpaper,    tags : [ "user", "user-wallpaper",    "user-personalization" ] }
    - { role : danbohea.dock-items, tags : [ "user", "user-dock",         "user-personalization" ] }
    - { role : user/applications,   tags : [ "user", "user-applications", "user-personalization" ] }

  # add misc task below, try to use roles where possibe.
  # https://galaxy.ansible.com/list#/roles
